CREATE TABLE [dbo].[@Template_SIE4_Trans]
(
[InstanceID] [int] NOT NULL,
[JobID] [int] NOT NULL,
[Param] [nvarchar] (50) NOT NULL,
[Seq] [nvarchar] (50) NOT NULL,
[Ver] [nvarchar] (50) NOT NULL,
[Trans] [int] NOT NULL,
[Account] [nvarchar] (50) NOT NULL,
[DimCode_01] [nvarchar] (50) NULL,
[ObjectCode_01] [nvarchar] (50) NULL,
[DimCode_02] [nvarchar] (50) NULL,
[ObjectCode_02] [nvarchar] (50) NULL,
[DimCode_03] [nvarchar] (50) NULL,
[ObjectCode_03] [nvarchar] (50) NULL,
[DimCode_04] [nvarchar] (50) NULL,
[ObjectCode_04] [nvarchar] (50) NULL,
[DimCode_05] [nvarchar] (50) NULL,
[ObjectCode_05] [nvarchar] (50) NULL,
[DimCode_06] [nvarchar] (50) NULL,
[ObjectCode_06] [nvarchar] (50) NULL,
[DimCode_07] [nvarchar] (50) NULL,
[ObjectCode_07] [nvarchar] (50) NULL,
[DimCode_08] [nvarchar] (50) NULL,
[ObjectCode_08] [nvarchar] (50) NULL,
[DimCode_09] [nvarchar] (50) NULL,
[ObjectCode_09] [nvarchar] (50) NULL,
[DimCode_10] [nvarchar] (50) NULL,
[ObjectCode_10] [nvarchar] (50) NULL,
[DimCode_11] [nvarchar] (50) NULL,
[ObjectCode_11] [nvarchar] (50) NULL,
[DimCode_12] [nvarchar] (50) NULL,
[ObjectCode_12] [nvarchar] (50) NULL,
[DimCode_13] [nvarchar] (50) NULL,
[ObjectCode_13] [nvarchar] (50) NULL,
[DimCode_14] [nvarchar] (50) NULL,
[ObjectCode_14] [nvarchar] (50) NULL,
[DimCode_15] [nvarchar] (50) NULL,
[ObjectCode_15] [nvarchar] (50) NULL,
[DimCode_16] [nvarchar] (50) NULL,
[ObjectCode_16] [nvarchar] (50) NULL,
[DimCode_17] [nvarchar] (50) NULL,
[ObjectCode_17] [nvarchar] (50) NULL,
[DimCode_18] [nvarchar] (50) NULL,
[ObjectCode_18] [nvarchar] (50) NULL,
[DimCode_19] [nvarchar] (50) NULL,
[ObjectCode_19] [nvarchar] (50) NULL,
[DimCode_20] [nvarchar] (50) NULL,
[ObjectCode_20] [nvarchar] (50) NULL,
[Amount] [decimal] (18, 2) NOT NULL,
[Date] [int] NOT NULL,
[Description] [nvarchar] (255) NULL,
[Inserted] [datetime] NOT NULL CONSTRAINT [DF_SIE4_Trans_Inserted] DEFAULT (getdate()),
[InsertedBy] [nvarchar] (100) NOT NULL
)
GO
ALTER TABLE [dbo].[@Template_SIE4_Trans] ADD CONSTRAINT [PK_SIE4_Trans] PRIMARY KEY CLUSTERED ([JobID], [Param], [Seq], [Ver], [Trans])
GO
