CREATE TABLE [dbo].[_sega_Time]
(
[MemberId] [bigint] NULL,
[Label] [nvarchar] (255) NOT NULL,
[Description] [nvarchar] (512) NOT NULL,
[HelpText] [nvarchar] (1024) NULL,
[Level] [nvarchar] (50) NULL,
[NumberOfDays] [int] NULL,
[PeriodEndDate] [nvarchar] (10) NULL,
[PeriodStartDate] [nvarchar] (10) NULL,
[RNodeType] [nvarchar] (2) NULL,
[RowOrder] [int] NULL,
[SBZ] [bit] NULL,
[SendTo_MemberId] [bigint] NULL,
[SendTo] [nvarchar] (255) NULL,
[TimeFiscalPeriod_MemberId] [bigint] NULL,
[TimeFiscalPeriod] [nvarchar] (255) NULL,
[TimeFiscalQuarter_MemberId] [bigint] NULL,
[TimeFiscalQuarter] [nvarchar] (255) NULL,
[TimeFiscalSemester_MemberId] [bigint] NULL,
[TimeFiscalSemester] [nvarchar] (255) NULL,
[TimeFiscalTertial_MemberId] [bigint] NULL,
[TimeFiscalTertial] [nvarchar] (255) NULL,
[TimeFiscalYear_MemberId] [bigint] NULL,
[TimeFiscalYear] [nvarchar] (255) NULL,
[TimeMonth_MemberId] [bigint] NULL,
[TimeMonth] [nvarchar] (255) NULL,
[TimeQuarter_MemberId] [bigint] NULL,
[TimeQuarter] [nvarchar] (255) NULL,
[TimeSemester_MemberId] [bigint] NULL,
[TimeSemester] [nvarchar] (255) NULL,
[TimeTertial_MemberId] [bigint] NULL,
[TimeTertial] [nvarchar] (255) NULL,
[TimeYear_MemberId] [bigint] NULL,
[TimeYear] [nvarchar] (255) NULL,
[PresentationYN] [bit] NULL
)
GO
