IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'DSPCLOUD\peder')
CREATE LOGIN [DSPCLOUD\peder] FROM WINDOWS
GO
CREATE USER [DSPCLOUD\peder] FOR LOGIN [DSPCLOUD\peder]
GO
GRANT CONNECT TO [DSPCLOUD\peder]
